/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Test;

public class App {
  
    public static void main(String[] args) {
        
        Veg f1 = new Veg(true,"daal", 120);
        Food f2 = new Food("roti",20);
        NonVeg f3 = new NonVeg("meat","chiken",450);
        Vegetables f4 = new Vegetables("green",true,"methi",20);
        Grains f5 = new Grains(true,true,"wheat",100);
        Meat f6 = new Meat(55.5,"meat","mutton",500);
        SeaFood f7 = new SeaFood("salt water","water animal","crabs",700);
        
        System.out.println(f1.toString());
        System.out.println(f2.toString());
        System.out.println(f3.toString());
        System.out.println(f4.toString());
        System.out.println(f5.toString());
        System.out.println(f6.toString());
        System.out.println(f7.toString());
    }
}
